name: CI

on:
  push:
    branches: [ feature/devops-e2e-deployment, develop, main ]
  pull_request:
    branches: [ feature/devops-e2e-deployment, develop, main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Test For branch name
      if: contains(github.ref, 'feature')
      run: echo "I only run if the branch has feature in its name!"  
    - name: Build and Test
      run: ./build.ps1 ci
      shell: pwsh
